{{- if .Values.job.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "llm-d-infrastructure.fullname" . }}-installer
  labels:
    {{- include "llm-d-infrastructure.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "llm-d-infrastructure.fullname" . }}-installer
subjects:
  - kind: ServiceAccount
    name: {{ include "llm-d-infrastructure.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
