{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "model-serving-engine.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "model-serving-engine.labels" . | nindent 4 }}
    release: {{ .Values.serviceMonitor.releaseLabel | default "prometheus" | quote }}
  annotations:
    {{- include "model-serving-engine.annotations" . | nindent 4 }}
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    matchLabels:
      {{- include "model-serving-engine.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Values.global.namespace }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path | default "/metrics" }}
      interval: {{ .Values.serviceMonitor.interval | default "10s" }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | default "5s" }}
      honorLabels: true
      {{- if .Values.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml .Values.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
{{- end }}