{{- if and .Values.router.enabled .Values.router.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "llm-d.router.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "llm-d.labels" . | nindent 4 }}
    release: {{ .Values.router.serviceMonitor.releaseLabel }}
spec:
  selector:
    matchLabels:
      {{- include "llm-d.selectorLabels" . | nindent 6 }}
      component: router
  endpoints:
    - path: {{ .Values.router.serviceMonitor.path }}
      port: metrics
      interval: {{ .Values.router.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.router.serviceMonitor.scrapeTimeout }}
{{- end }}
---
{{- if and .Values.kvCacheIndexer.enabled .Values.kvCacheIndexer.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "llm-d.indexer.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "llm-d.labels" . | nindent 4 }}
    release: {{ .Values.kvCacheIndexer.serviceMonitor.releaseLabel }}
spec:
  selector:
    matchLabels:
      {{- include "llm-d.selectorLabels" . | nindent 6 }}
      component: indexer
  endpoints:
    - path: {{ .Values.kvCacheIndexer.serviceMonitor.path }}
      port: metrics
      interval: {{ .Values.kvCacheIndexer.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.kvCacheIndexer.serviceMonitor.scrapeTimeout }}
{{- end }}